# Numpy Basics

In [1]:
import numpy as np

In [2]:
np.__version__

'1.25.1'

In [3]:
a_list = [1, 2, 3 ,4, 5, 6, 7, 8, 9, 10]
a_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
type(a_list)

list

In [5]:
a_arr = np.array(a_list)
a_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
type(a_arr)

numpy.ndarray

In [7]:
len(a_list)

10

In [8]:
a_arr.shape

(10,)

In [9]:
a_arr.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
a_arr.reshape(5, 2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
a_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a_arr = a_arr.reshape(2, 5)
a_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
a_arr.T # Tranposing the matrix

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [14]:
a_arr.T.T

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
np.arange(100)
# Numpy way of generating serial numbers, similar to range in python

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
a = np.arange(100, 300, 2) # start, stop, step
a

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202,
       204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228,
       230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
       256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280,
       282, 284, 286, 288, 290, 292, 294, 296, 298])

In [17]:
a.shape

(100,)

In [18]:
a_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
for i in range(len(a_list)):
    a_list[i] += 1
a_list

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [20]:
a + 18

array([118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142,
       144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168,
       170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194,
       196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220,
       222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246,
       248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272,
       274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298,
       300, 302, 304, 306, 308, 310, 312, 314, 316])

In [21]:
a - 23

array([ 77,  79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101,
       103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127,
       129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153,
       155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179,
       181, 183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205,
       207, 209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231,
       233, 235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255, 257,
       259, 261, 263, 265, 267, 269, 271, 273, 275])

In [22]:
a

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202,
       204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228,
       230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
       256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280,
       282, 284, 286, 288, 290, 292, 294, 296, 298])

In [24]:
a / 100

array([1.  , 1.02, 1.04, 1.06, 1.08, 1.1 , 1.12, 1.14, 1.16, 1.18, 1.2 ,
       1.22, 1.24, 1.26, 1.28, 1.3 , 1.32, 1.34, 1.36, 1.38, 1.4 , 1.42,
       1.44, 1.46, 1.48, 1.5 , 1.52, 1.54, 1.56, 1.58, 1.6 , 1.62, 1.64,
       1.66, 1.68, 1.7 , 1.72, 1.74, 1.76, 1.78, 1.8 , 1.82, 1.84, 1.86,
       1.88, 1.9 , 1.92, 1.94, 1.96, 1.98, 2.  , 2.02, 2.04, 2.06, 2.08,
       2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 , 2.22, 2.24, 2.26, 2.28, 2.3 ,
       2.32, 2.34, 2.36, 2.38, 2.4 , 2.42, 2.44, 2.46, 2.48, 2.5 , 2.52,
       2.54, 2.56, 2.58, 2.6 , 2.62, 2.64, 2.66, 2.68, 2.7 , 2.72, 2.74,
       2.76, 2.78, 2.8 , 2.82, 2.84, 2.86, 2.88, 2.9 , 2.92, 2.94, 2.96,
       2.98])