In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
labels = np.array(['Nepal', 'India', 'China', 'Nepal', 'China',
                  'Nepal', 'India', 'China', 'Nepal', 'China'])

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [4]:
label_encoder = LabelEncoder()
one_hot_encoder = OneHotEncoder(sparse_output=False)

In [5]:
labels

array(['Nepal', 'India', 'China', 'Nepal', 'China', 'Nepal', 'India',
       'China', 'Nepal', 'China'], dtype='<U5')

In [6]:
label_encoder.fit_transform(labels)

array([2, 1, 0, 2, 0, 2, 1, 0, 2, 0], dtype=int64)

In [7]:
label_encoder.classes_

array(['China', 'India', 'Nepal'], dtype='<U5')

In [8]:
labels.reshape(-1, 1)

array([['Nepal'],
       ['India'],
       ['China'],
       ['Nepal'],
       ['China'],
       ['Nepal'],
       ['India'],
       ['China'],
       ['Nepal'],
       ['China']], dtype='<U5')

In [9]:
one_hot_encoder.fit_transform(labels.reshape(-1, 1))

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

# Data Scaling

In [10]:
np.random.seed(666)

In [11]:
data = np.random.randint(low=20, high=100, size=15)
data

array([22, 65, 50, 82, 90, 93, 50, 56, 81, 71, 80, 48, 34, 83, 36])

In [12]:
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, StandardScaler, RobustScaler

# Min Max Scaler : $\frac{X - min}{max - min}$ : $\frac{X - 22}{93 - 22}$
# MaxAbs Scaler: $\frac{X}{max}$
# Standard Scaler : $\frac{X - \mu}{\sigma}$

# Robust Scaler : $\frac{X - q_1}{q_3 - q_1}$ 